source "https://rubygems.org"

gem "aws-sdk-s3"
gem "aws-sdk-sqs"
gem "byebug"
gem "httparty"
gem "m"
gem "minitest"
gem "parslet"
gem "rake"
gem "rlua", git: "https://github.com/whitequark/rlua", branch: "master"
gem "sinatra"
gem "zeitwerk"
