name: Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install lua-dev
      run: |
        sudo apt -y install liblua5.3-dev
    - name: Install gems
      run: |
        gem install bundler
        bundler install
    - name: Run tests
      run: |
        bundle exec rake
